### ISSUE TITLE
 snips-injection package replace snips-asr-injection

### ISSUE THREAD

**Issue by biemster** [syntithenai/opensnips#5]
https://github.com/syntithenai/opensnips/blob/5c896fd916b04ac7be1375bcad64c58e8238147e/docker-images/snips/Dockerfile#L34

https://forum.snips.ai/t/error-on-apt-get-update/480

also, this command is run twice (also on line 35)

**Comment by syntithenai** [comment]
fixed in Dockerfile for snips docker-image, thanks

Steve
